version: '3.5'
services:
    front:
        container_name: front
        volumes:
          - '.:/usr/src/app'
          - '/usr/src/app/node_modules'
        build:
            context: ./front-docker-app
            dockerfile: Dockerfile-front
        depends_on:
            - back
        ports:
            - "5000:80"
        links:
            - "back"
    back:
        container_name: back
        build:
            context: .
            dockerfile: Dockerfile-back
        ports:
            - "8080:8080"            